name: Run AOC
on: [push]

jobs:
  aoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10.x"
      - name: Install poetry
        run: pip3 install poetry
      - name: Setup environment
        run: poetry install
      - name: Run all days
        run: poetry run python .github/workflows/all.py > aoc2021.log
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: aoc2021
          path: aoc2021.log
